### PR TITLE
Fix error during setup "[...] DatacenterViewInstaller [...] Unknown attribute locationtype_id from class Location"

### PR DESCRIPTION
**Pull request by accognet**
Fix this error during setup :
image
with the extensions : combodo-location-hierarchy and molkobain-datacenter-view-extended

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello Anne-Catherine :)

Thanks for the PR, could detail how to reproduce this?
- iTop version
- molkobain-datacenter-view version (precise if it's the module or extension version)
- combodo-location-hierarchy version
- Is this happening due to a customer's delta?

Also, would it be possible to have the zip package of this version of _Location hierarchy_ so I can qualify and ensure it's fixed when packaging the new version?

**Comment by accognet** [comment]
This happened on a client instance on iTop 3.1.1 with Datacenter view extended v1.10.1 and Location hierarchy 1.0.2 
I have reproduced on my pc without any customization on iTop3.2  with Datacenter view extended v1.11.1 and Location hierarchy 1.0.2

**Comment by Molkobain** [comment]
> Also, would it be possible to have the zip package of this version of _Location hierarchy_ so I can qualify and ensure it's fixed when packaging the new version?

Can you check if this is possible? Otherwise I won't be able to confirm the new package it ok.

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
PR merged, I'll prepare the `molkobain-datacenter-view` and `molkobain-datacenter-view-extended` packages.
Thanks! 🙌

**Pull request merged**
